### PR TITLE
ADS-3394 remove modules Salish no longer needs

### PR DESCRIPTION
**Pull request by martiantim**

### CODE REVIEW

**Comment by brian-themaven** [comment]
Do we also need to remove these bidders from web-skagit/src/helpers/PrebidHelper.js and remove the channel flags if any channels are using these bidders via component/Flags/Flag.js?

**Comment by martiantim** [comment]
@bradchoate good catch, do you think we should just check in the reverse of that diff or remove that change next time we rebase on upstream master or something else?

**Comment by martiantim** [comment]
@brian-themaven good call, I added that to my change of web-skagit

**Comment by bradchoate** [comment]
@martiantim I'm okay with either. If you want to defer it, I'd just ticket it with a 'techdebt' label in JIRA.

**Comment by martiantim** [comment]
@bradchoate Thanks, added a ticket

**Pull request merged**
