### PR TITLE
ADS-6193: Various arrays tracked in the Prebid data sent to LiftIgniter do not zip together correctly

### PR DESCRIPTION
**Pull request by elliotz1120**
Reshaped the various arrays tracked in the Prebid data.

Ticket: https://mavencorp.atlassian.net/browse/ADS-6193

### CODE REVIEW

**Comment by partha0solapurkar** [comment]
I think you may have found a simpler way of doing this compared to what I had suggested!

Inlining `getCommonEventToSend` is a good start, because the correct logic for auctionInit and auctionEnd is likely to be different due to the subtleties related to `(adUnit.mediaTypes.video?.context === 'adpod')`.

However, the change as it stands currently doesn't address the problem of some of the arrays not matching up correctly.
For instance, in `summarizeAuctionInit`, if the length of `durationRangeSec` is different from 1, then adUnitCodes, zoneIndexes, zoneNames, podPos will have a (common) length that is different from the (common) length of `bidderss` and `floorss`.

Also, in the data sent by `summarizeAuctionEnd`, I see cases where `bidders.size` > `bid_statuss.size` = `bid_amounts.size` = `bid_response_times` etc (the "inner arrays", not the "outer arrays of arrays"). My naive guess is that something may be going wrong while delegating to `getBidStatusAmtsAndResponseTime`, but I don't see how this could be happening, because `bidders.push` is happening on the same level as `bid_response_times.push` and the others.

**Comment by AritraSengupta** [comment]
@partha0solapurkar I think this where a test file really makes sense, I wonder if we can add test cases and make sure that we are getting the outputs that we need. Also, for now to mitigate the issue that you are talking about @partha0solapurkar do you think we can pass like an `undefined` value when the data for the corresponding values are not found so that on the backend you know which data did not match up? We can create a separate ticket to investigate why the data is not coming through.

**Comment by partha0solapurkar** [comment]
`null` would be better than `undefined`, because the scala backend that processes the data and the bigquery tables that record the data are both strongly and statically typed, so they won't be able to mix numbers and `"undefined"`, but they will allow mixing numbers and `null`

**Comment by partha0solapurkar** [comment]
I see there's a test file here: https://github.com/themaven-net/Prebid.js/blob/stable/test/spec/modules/mavenDistributionAnalyticsAdapter_spec.js

Adding tests sounds like a good idea. I can add additional tests as I encounter examples in the wild. Currently no prebid calls are being made from pages that have more than one ad pods, so we should probably use a made up a test case where `durationRangeSec` has size two.

**Review by partha0solapurkar — APPROVED** [review]
Thanks @elliotz1120 , I think this should ensure that the outer arrays all have the same size

**Pull request merged**
